development:
  adapter: postgresql
  database: mathsonline_development
  pool: 5
  timeout: 5000
  port: 5432
  username: elneelo
  password: Snowpatrol

test:
  adapter: postgresql
  database: mathsonline_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mathsonline_production
  pool: 5
  timeout: 5000